[package]
name = "fql"
version = "0.1.0"
edition = "2024"

[dependencies]
hostios-domain = { version = "0.1.0", path = "../domain" }
serde.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs"] }
