[package]
name = "hostios-application"
version = "0.1.0"
edition = "2024"

[dependencies]
async-recursion = "1.1.1"
hostios-domain = { version = "0.1.0", path = "../domain" }

thiserror.workspace = true
sqlx.workspace = true
tokio.workspace = true
