[package]
name = "hostios-application"
version = "0.1.0"
edition = "2024"

[dependencies]
async-recursion = "1.1.1"
hostios-domain = { version = "0.1.0", path = "../domain" }
tokio = { version = "1.47.0", features = ["fs"] }

thiserror.workspace = true
sqlx.workspace = true
