[workspace]
resolver = "3"
members = ["domain", "application", "presentation", "daemon"]

[workspace.dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
thiserror = "2.0.12"
