[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
hostios-application = { version = "0.1.0", path = "../application" }
notify = { version = "8.1.0", features = [] }
tokio = { version = "1.47.0", features = ["rt", "macros", "rt-multi-thread"] }
